CREATE DEFINER=`root`@`localhost` PROCEDURE `p_fpago_inverso`(
	vSOLICITADO DECIMAL(10,2),
    vCUOTAS INT(11),
    vVALOR_CUOTA DECIMAL(10,2),
    vPORCENTAJE_ADICIONAL DECIMAL(10,3),
    vIVA DECIMAL(10,2)
)
BEGIN
	-- CALL p_fpago_inverso(1000,3,487.50,18,21);
	DECLARE vVALOR_CUOTA_REFERENCIA DECIMAL(10,2);
    DECLARE vTASA_AUX DECIMAL(10,2);
    DECLARE vINTENTOS INT;
    
    SET vTASA_AUX = 0;
	
    
    SET vINTENTOS = 10000;
    
    loop_label:  LOOP
    
		SET vTASA_AUX = vTASA_AUX + 0.01;
        SELECT F_PAGO_CUOTA(vSOLICITADO,vCUOTAS,vTASA_AUX,vPORCENTAJE_ADICIONAL,vIVA,'CUO') into vVALOR_CUOTA_REFERENCIA;
		SET @DIFF = vVALOR_CUOTA_REFERENCIA - vVALOR_CUOTA;
        IF @DIFF = 0 THEN
			LEAVE  loop_label;
        END IF;
		SET vINTENTOS = vINTENTOS - 1;
        IF vINTENTOS = 0 THEN
			LEAVE  loop_label;
        END IF;
		ITERATE  loop_label;
    
    END LOOP;
    
    CALL p_fpago(vSOLICITADO,vCUOTAS,vTASA_AUX,vPORCENTAJE_ADICIONAL,vIVA);

END