CREATE DEFINER=`root`@`localhost` PROCEDURE `p_fpago`(
	vSOLICITADO DECIMAL(10,2),
    vCUOTAS INT(11),
    vTASA DECIMAL(10,4),
    vPORCENTAJE_ADICIONAL DECIMAL(10,3),
    vIVA DECIMAL(10,2)
)
BEGIN

    
	SET @CAPITAL = vSOLICITADO * (1 + vPORCENTAJE_ADICIONAL);

	SET vSOLICITADO = ROUND(vSOLICITADO,2);
    SET @CAPITAL = ROUND(@CAPITAL,2);
    
    SELECT F_PAGO_CUOTA(vSOLICITADO,vCUOTAS,vTASA,vPORCENTAJE_ADICIONAL,vIVA,'CUO') INTO @VALOR_CUOTA;
    SELECT F_PAGO_CUOTA(vSOLICITADO,vCUOTAS,vTASA,vPORCENTAJE_ADICIONAL,vIVA,'CAP') INTO @CAPITAL_CUOTA;
    SELECT F_PAGO_CUOTA(vSOLICITADO,vCUOTAS,vTASA,vPORCENTAJE_ADICIONAL,vIVA,'INT') INTO @INTERES;
    SELECT F_PAGO_CUOTA(vSOLICITADO,vCUOTAS,vTASA,vPORCENTAJE_ADICIONAL,vIVA,'IVA') INTO @IVA;
    SELECT F_PAGO_CUOTA(vSOLICITADO,vCUOTAS,vTASA,vPORCENTAJE_ADICIONAL,vIVA,'ADI') INTO @ADICIONALES;

    SET @VALOR_CUOTA = ROUND(@VALOR_CUOTA,2);
    SET @CAPITAL_CUOTA = ROUND(@CAPITAL_CUOTA,2);
    SET @INTERES = ROUND(@INTERES,2);
    SET @ADICIONALES = ROUND(@ADICIONALES,2);
    SET @IVA = ROUND(@IVA,2);
    
    SELECT vSOLICITADO AS PERCIBIDO,@CAPITAL AS SOLICITADO,vCUOTAS AS CUOTAS,
    @VALOR_CUOTA AS CUOTA,@CAPITAL_CUOTA AS CAPITAL, @INTERES AS INTERES,
    @IVA AS IVA_CUOTA,@ADICIONALES AS ADICIONAL;
    

END