CREATE DEFINER=`root`@`127.0.0.1` PROCEDURE `SP_LIQUIDA_DEUDA_CBU_GESTION_MORA`(
vSOCIO_ID INT(11),
vORGANISMO VARCHAR(12),
vLIQUIDACION_ID INT(11)
)
BEGIN
DECLARE l_last_row INT DEFAULT 0;
DECLARE vID INT(11);
DECLARE vIMPORTE_DEBITO DECIMAL(10,2);
DECLARE vIMPORTE_DEBITO_CALCULADO DECIMAL(10,2);
DECLARE vFORMULA TEXT;
DECLARE cursor_mora CURSOR FOR 
SELECT id,importe_adebitar FROM liquidacion_socios
where liquidacion_id = vLIQUIDACION_ID and socio_id = vSOCIO_ID
and periodo = 0;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET l_last_row=1;


SET vIMPORTE_DEBITO_CALCULADO = 0;
SET @LIMITE_1 = 100;
SET @LIMITE_2 = 200;
SET @TOPE_DEBITO_MAXIMO = 800;
SET @TOPE_2 = 0;

SELECT entero_1,entero_2,decimal_1,decimal_2 INTO @LIMITE_1,@LIMITE_2,@TOPE_DEBITO_MAXIMO,@TOPE_2
FROM global_datos WHERE id = vORGANISMO;


OPEN cursor_mora;
c1_loop: LOOP
	FETCH cursor_mora INTO vID,vIMPORTE_DEBITO;
    
	IF (l_last_row = 1) THEN
		LEAVE c1_loop; 
	END IF;	      
    SET vFORMULA = '';
    SET vIMPORTE_DEBITO_CALCULADO = vIMPORTE_DEBITO;
    
    IF @LIMITE_1 >= vIMPORTE_DEBITO THEN
		SET vIMPORTE_DEBITO_CALCULADO = vIMPORTE_DEBITO;
        SET vFORMULA = CONCAT(vIMPORTE_DEBITO,' <' , @LIMITE_1,' ==> IMPORTE A DEBITAR: ',vIMPORTE_DEBITO_CALCULADO,' (TOTAL ATRASO)');
    END IF;
    

    IF @LIMITE_1 < vIMPORTE_DEBITO AND vIMPORTE_DEBITO <= @LIMITE_2 THEN
		SET vIMPORTE_DEBITO_CALCULADO = vIMPORTE_DEBITO / 2;
        SET vFORMULA = CONCAT(@LIMITE_1,' < ',vIMPORTE_DEBITO,' <= ' , @LIMITE_2,' ==> IMPORTE A DEBITAR: ',vIMPORTE_DEBITO_CALCULADO,' (TOTAL ATRASO / 2)');
    END IF;
    
    IF vIMPORTE_DEBITO > @LIMITE_2 THEN
		SET vIMPORTE_DEBITO_CALCULADO = vIMPORTE_DEBITO / 3;
        SET vFORMULA = CONCAT(vIMPORTE_DEBITO,' > ' , @LIMITE_2,' ==> IMPORTE A DEBITAR: ',vIMPORTE_DEBITO_CALCULADO,' (TOTAL ATRASO / 3)');
    END IF; 
    
    -- CONTROL DEL TOPE DE DEBITO CBU
    IF @TOPE_DEBITO_MAXIMO < vIMPORTE_DEBITO_CALCULADO THEN
		SET vIMPORTE_DEBITO_CALCULADO = @TOPE_DEBITO_MAXIMO;
        SET vFORMULA = CONCAT(vFORMULA,'\nCONTROL MONTO MAXIMO DEBITO CBU == > IMPORTE A DEBITAR: ',vIMPORTE_DEBITO_CALCULADO);
    END IF;

	update liquidacion_socios set importe_adebitar = vIMPORTE_DEBITO_CALCULADO,
    formula_criterio_deuda = vFORMULA where id = vID;
    
END LOOP c1_loop;
END