CREATE DEFINER=`root`@`localhost` PROCEDURE `sigem_db`.`SP_LIMPIA_BASE`(IN vPIN CHAR(12))
BEGIN
IF  vPIN = 'SIGEM*180407' THEN 
	delete from asincrono_temporal_detalles;
	delete from asincrono_temporales;
	delete from asincrono_errores;
	delete from asincronos;
	alter table asincrono_temporal_detalles AUTO_INCREMENT = 1;
	alter table asincrono_temporales AUTO_INCREMENT = 1;
	alter table asincrono_errores AUTO_INCREMENT = 1;
	alter table asincronos AUTO_INCREMENT = 1;
	delete from liquidacion_socio_rendiciones;
	delete from liquidacion_intercambio_registro_procesados;
	delete from liquidacion_intercambio_registros;
	delete from liquidacion_intercambios;
	delete from liquidacion_socio_envio_registros;
	delete from liquidacion_socio_envios;
	delete from liquidacion_socios;
	delete from liquidacion_cuotas;
    delete from liquidacion_socio_scores;
	delete from liquidaciones;
	alter table liquidacion_socio_rendiciones AUTO_INCREMENT = 1;
	alter table liquidacion_intercambio_registro_procesados AUTO_INCREMENT = 1;
	alter table liquidacion_intercambio_registros AUTO_INCREMENT = 1;
	alter table liquidacion_intercambios AUTO_INCREMENT = 1;
	alter table liquidacion_socio_envio_registros AUTO_INCREMENT = 1;
	alter table liquidacion_socio_envios AUTO_INCREMENT = 1;
	alter table liquidacion_socios AUTO_INCREMENT = 1;
	alter table liquidacion_cuotas AUTO_INCREMENT = 1;
    alter table liquidacion_socio_scores AUTO_INCREMENT = 1;
	alter table liquidaciones AUTO_INCREMENT = 1;   
	delete from mutual_adicional_pendientes;
	delete from mutual_adicionales;
	alter table mutual_adicional_pendientes AUTO_INCREMENT = 1;
	alter table mutual_adicionales AUTO_INCREMENT = 1;
	update orden_descuentos set anterior_orden_descuento_id = null, nueva_orden_descuento_id = null, mutual_producto_solicitud_id = NULL;
	delete from cancelacion_orden_cuotas;
	delete from cancelacion_ordenes;
	delete from orden_descuento_cobro_cuotas;
	delete from orden_descuento_cobros;
	delete from orden_caja_cobro_cuotas;
	delete from orden_caja_cobros;
	delete from orden_descuento_cuotas;
    delete from mutual_producto_solicitud_estados;
	delete from mutual_producto_solicitud_instruccion_pagos;
	delete from mutual_producto_solicitud_documentos;
	delete from mutual_producto_solicitud_cancelaciones;
	delete from mutual_producto_solicitud_pagos;
	delete from mutual_producto_solicitud_preproceso;
	delete from mutual_producto_solicitudes;
	delete from mutual_productos;
	delete from mutual_servicio_solicitud_adicionales;
	delete from mutual_servicio_solicitudes;
	delete from mutual_servicio_valores;
	delete from mutual_servicios;
	delete from orden_descuentos;
	delete from orden_pago_formas;
	delete from orden_pago_facturas;
	delete from orden_pago_detalles;
	delete from orden_pagos;
	delete from recibo_formas;
	delete from recibo_facturas;
	delete from recibo_detalles;
	delete from recibos;
	delete from banco_cuenta_movimientos;
	delete from banco_cuentas;
	delete from banco_cheque_terceros;
	delete from banco_cuenta_chequeras;
	delete from co_asiento_renglones;
	delete from co_asientos;
	delete from co_plan_cuentas;
	delete from co_ejercicios;
	update tipo_documentos set numero = 0;
	alter table cancelacion_orden_cuotas AUTO_INCREMENT = 1;
	alter table cancelacion_ordenes AUTO_INCREMENT = 1;
	alter table orden_descuento_cobro_cuotas AUTO_INCREMENT = 1;
	alter table orden_descuento_cobros AUTO_INCREMENT = 1;
	alter table orden_caja_cobro_cuotas AUTO_INCREMENT = 1;
	alter table orden_caja_cobros AUTO_INCREMENT = 1;
	alter table orden_descuento_cuotas AUTO_INCREMENT = 1;
    alter table mutual_producto_solicitud_estados AUTO_INCREMENT = 1;
	alter table mutual_producto_solicitud_instruccion_pagos AUTO_INCREMENT = 1;
	alter table mutual_producto_solicitud_documentos AUTO_INCREMENT = 1;
	alter table mutual_producto_solicitud_cancelaciones AUTO_INCREMENT = 1;
	alter table mutual_producto_solicitud_pagos AUTO_INCREMENT = 1;
	alter table mutual_producto_solicitud_preproceso AUTO_INCREMENT = 1;
	alter table mutual_producto_solicitudes AUTO_INCREMENT = 1;
	alter table mutual_productos AUTO_INCREMENT = 1;
	alter table mutual_servicio_solicitud_adicionales AUTO_INCREMENT = 1;
	alter table mutual_servicio_solicitudes AUTO_INCREMENT = 1;
	alter table mutual_servicio_valores AUTO_INCREMENT = 1;
	alter table mutual_servicios AUTO_INCREMENT = 1;
	alter table orden_descuentos AUTO_INCREMENT = 1;
	alter table orden_pago_formas AUTO_INCREMENT = 1;
	alter table orden_pago_facturas AUTO_INCREMENT = 1;
	alter table orden_pago_detalles AUTO_INCREMENT = 1;
	alter table orden_pagos AUTO_INCREMENT = 1;
	alter table recibo_formas AUTO_INCREMENT = 1;
	alter table recibo_facturas AUTO_INCREMENT = 1;
	alter table recibo_detalles AUTO_INCREMENT = 1;
	alter table recibos AUTO_INCREMENT = 1;
	alter table banco_cuenta_movimientos AUTO_INCREMENT = 1;
	alter table banco_cuentas AUTO_INCREMENT = 1;
	alter table banco_cheque_terceros AUTO_INCREMENT = 1;
	alter table banco_cuenta_chequeras AUTO_INCREMENT = 1;
	alter table co_asiento_renglones AUTO_INCREMENT = 1;
	alter table co_asientos AUTO_INCREMENT = 1;
	alter table co_plan_cuentas AUTO_INCREMENT = 1;
	alter table co_ejercicios AUTO_INCREMENT = 1;   
	delete from vendedor_remitos;
	delete from vendedor_proveedor_planes;
	delete from vendedores;
	alter table vendedor_remitos AUTO_INCREMENT = 1;
	alter table vendedor_proveedor_planes AUTO_INCREMENT = 1;
	alter table vendedores AUTO_INCREMENT = 1;
	delete from proveedor_liquidaciones;
	delete from proveedor_comisiones where proveedor_id <> 18;
	delete from proveedor_facturas;
	delete from proveedor_grilla_cuotas;
	delete from proveedor_grillas;
	delete from proveedor_vencimientos where proveedor_id <> 18;
	delete from proveedor_tipo_asiento_renglones;
	delete from proveedor_tipo_asientos;
	delete from proveedor_plan_organismos;
	delete from proveedor_plan_grilla_cuotas;
	delete from proveedor_plan_grillas;
    delete from proveedor_plan_anexos;
	delete from proveedor_planes;
    delete from proveedor_prioridad_imputa_organismos;
	delete from proveedores where id <> 18;
	delete from cliente_tipo_asiento_renglones;
	delete from cliente_tipo_asientos;
	delete from cliente_factura_detalles;
	delete from cliente_facturas;
	delete from clientes;
	alter table proveedor_liquidaciones AUTO_INCREMENT = 1;
	alter table proveedor_comisiones AUTO_INCREMENT = 19;
	alter table proveedor_facturas AUTO_INCREMENT = 1;
	alter table proveedor_grilla_cuotas AUTO_INCREMENT = 1;
	alter table proveedor_grillas AUTO_INCREMENT = 1;
	alter table proveedor_vencimientos AUTO_INCREMENT = 19;
	alter table proveedor_tipo_asiento_renglones AUTO_INCREMENT = 1;
	alter table proveedor_tipo_asientos AUTO_INCREMENT = 1;
	alter table proveedor_plan_organismos AUTO_INCREMENT = 1;
	alter table proveedor_plan_grilla_cuotas AUTO_INCREMENT = 1;
	alter table proveedor_plan_grillas AUTO_INCREMENT = 1;
	alter table proveedor_planes AUTO_INCREMENT = 1;
    alter table proveedor_prioridad_imputa_organismos AUTO_INCREMENT = 1;
	alter table proveedores AUTO_INCREMENT = 19;
	alter table cliente_tipo_asiento_renglones AUTO_INCREMENT = 1;
	alter table cliente_tipo_asientos AUTO_INCREMENT = 1;
	alter table cliente_factura_detalles AUTO_INCREMENT = 1;
	alter table cliente_facturas AUTO_INCREMENT = 1;
	alter table clientes AUTO_INCREMENT = 19;   
	delete from socio_calificaciones;
	delete from socio_adicionales;
	delete from socio_convenio_cuotas;
	delete from socio_convenios;
	delete from socio_reintegro_pagos;
	delete from socio_reintegros;
	delete from socio_historicos;
	delete from socio_solicitudes;
	delete from socios;
	delete from persona_beneficio_compartidos;
	delete from persona_beneficios;
    delete from persona_novedades;
    delete from personas;
	alter table socio_calificaciones AUTO_INCREMENT = 1;
	alter table socio_adicionales AUTO_INCREMENT = 1;
	alter table socio_convenio_cuotas AUTO_INCREMENT = 1;
	alter table socio_convenios AUTO_INCREMENT = 1;
	alter table socio_reintegro_pagos AUTO_INCREMENT = 1;
	alter table socio_reintegros AUTO_INCREMENT = 1;
	alter table socio_historicos AUTO_INCREMENT = 1;
	alter table socio_solicitudes AUTO_INCREMENT = 1;
	alter table socios AUTO_INCREMENT = 1; 
    alter table persona_beneficio_compartidos AUTO_INCREMENT = 1;
    alter table persona_beneficios AUTO_INCREMENT = 1;
    alter table persona_novedades AUTO_INCREMENT = 1;
    alter table personas AUTO_INCREMENT = 1;
    delete from global_datos where id like 'MUTUPROD%' and id > 'MUTUPROD0003';
    /*
    delete from usuarios where usuario not in ('ADRIAN','JUANCA');
    -- update usuarios set password = sha1(CONCAT('DYhG93b0qyJfIwCreditxfs2guVoUubWwvniR2G0FgaC9mi',TRIM(usuario)));
	update proveedores set cuit = '30716025000',
	razon_social = 'DESCONTAR SAS', razon_social_resumida = 'DESCONTAR',
	calle = 'AVDA BELGRANO', numero_calle = '224', piso = '0', dpto = '2', 
    localidad = 'SALSIPUEDES',
    codigo_postal = '5113', barrio = '', email = 'alexisquiroga@hotmail.com', 
    telefono_movil = 'alexisquiroga@hotmail.com' where id = 18;
    */
END IF;
END