INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', '000', 'COBRADO', '1', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R02', 'CUENTA CERRADA O SUSPENDIDA', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R03', 'CUENTA INEXISTENTE', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R04', 'NRO DE CUENTA INVALIDO', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R05', 'ORDEN DE DIFERIMIENTO', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R06', 'DEFECTOS FORMALES', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R07', 'SOLICITUD DE LA ENTIDAD ORIGINANTE', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R08', 'ORDEN DE NO PAGAR', '0', 'MUTUCALISDEB');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R10', 'FALTA DE FONDOS', '0', 'MUTUCALIMORO');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R13', 'ENTIDAD DESTINO INEXISTENTE', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R14', 'ID CLIENTE / EMPRESA INCORRECTO', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R15', 'BAJA DEL SERVICIO', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R17', 'ERROR DE FORMATO', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R19', 'IMPORTE ERRONEO', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R20', 'MONEDA DISTINTA A LA CUENTA DE DEBITO', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R23', 'SUC. NO HABILITADA', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R24', 'TRANSACCION DUPLICADA', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R25', 'ERROR EN REGISTRO ADICIONAL', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R26', 'ERROR POR CAMPO MANDATARIO', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R28', 'RECHAZO PRIMER VENCIMIENTO', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R29', 'REVERSION YA EFECTUADA', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R75', 'FECHA INVALIDA', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R81', 'FUERZA MAYOR', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R87', 'MONEDA INVALIDA', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R89', 'ERRORES EN ADHESIONES', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R91', 'COD BCO INCOMP CON MONEDA TRANSAC.', '0', 'MUTUCALINORM');
INSERT INTO `banco_rendicion_codigos` (`banco_id`, `codigo`, `descripcion`, `indica_pago`, `calificacion_socio`) VALUES ('00007', 'R95', 'REVERSION RECEP PRESENT FUERA DE TERMINO', '0', 'MUTUCALINORM');
