/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  adrian
 * Created: 02/04/2019
 */

-- CREAR UNA BASE DE DATOS NUEVA PARA LOS HISTORICOS
CREATE DATABASE `sigemhisto_db`;


CREATE TABLE `liquidacion_historicos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) DEFAULT '0',
  `codigo_organismo` varchar(12) DEFAULT NULL,
  `sobre_pre_imputacion` tinyint(1) DEFAULT '0',
  `bloqueada` tinyint(1) DEFAULT '0',
  `cerrada` tinyint(1) DEFAULT '0',
  `en_proceso` tinyint(1) DEFAULT '1',
  `archivos_procesados` tinyint(1) DEFAULT '0',
  `imputada` tinyint(1) DEFAULT '0',
  `facturada` tinyint(1) DEFAULT '0',
  `periodo` varchar(6) DEFAULT NULL,
  `cuota_social_vencida` decimal(10,2) DEFAULT '0.00',
  `cuota_social_periodo` decimal(10,2) DEFAULT '0.00',
  `deuda_vencida` decimal(10,2) DEFAULT '0.00',
  `deuda_periodo` decimal(10,2) DEFAULT '0.00',
  `total_vencido` decimal(10,2) DEFAULT '0.00',
  `total_periodo` decimal(10,2) DEFAULT '0.00',
  `total` decimal(10,2) DEFAULT '0.00',
  `altas` int(11) DEFAULT '0',
  `registros_enviados` int(11) DEFAULT '0',
  `registros_recibidos` int(11) DEFAULT '0',
  `importe_recibido` decimal(10,2) DEFAULT '0.00',
  `importe_cobrado` decimal(10,2) DEFAULT '0.00',
  `importe_no_cobrado` decimal(10,2) DEFAULT '0.00',
  `importe_imputado` decimal(10,2) DEFAULT '0.00',
  `importe_reintegro` decimal(10,2) DEFAULT '0.00',
  `fecha_imputacion` date DEFAULT NULL,
  `recibo_id` int(11) DEFAULT '0',
  `asincrono_id` int(11) DEFAULT '0',
  `nro_recibo` varchar(50) DEFAULT NULL,
  `scoring` tinyint(4) NOT NULL DEFAULT '0',
  `user_created` varchar(50) DEFAULT NULL,
  `user_modified` varchar(50) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_periodo` (`periodo`,`id`,`codigo_organismo`),
  KEY `organism_temporal` (`codigo_organismo`,`periodo`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


-- drop table if exists liquidacion_cuota_historicos;

CREATE TABLE `liquidacion_cuota_historicos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `liquidacion_id` int(11) DEFAULT '0',
  `registro` int(11) DEFAULT '1',
  `mutual_adicional_pendiente_id` int(11) DEFAULT '0',
  `codigo_organismo` varchar(12) DEFAULT NULL,
  `socio_id` int(11) DEFAULT '0',
  `persona_beneficio_id` int(11) DEFAULT '0',
  `orden_descuento_id` int(11) DEFAULT '0',
  `orden_descuento_cuota_id` int(11) DEFAULT '0',
  `tipo_orden_dto` varchar(5) DEFAULT NULL,
  `tipo_producto` varchar(12) DEFAULT NULL,
  `tipo_cuota` varchar(12) DEFAULT NULL,
  `periodo_cuota` varchar(6) DEFAULT NULL,
  `proveedor_id` int(11) DEFAULT '0',
  `vencida` tinyint(1) DEFAULT '0',
  `importe` decimal(10,2) DEFAULT '0.00',
  `saldo_actual` decimal(10,2) DEFAULT '0.00',
  `importe_debitado` decimal(10,2) DEFAULT '0.00',
  `liquidacion_intercambio_id` int(11) DEFAULT '0',
  `para_imputar` tinyint(1) DEFAULT '0',
  `imputada` tinyint(1) DEFAULT '0',
  `orden_descuento_cobro_id` int(11) DEFAULT '0',
  `orden_descuento_cobro_cuota_id` int(11) DEFAULT '0',
  `proveedor_liquidacion_id` int(11) DEFAULT '0',
  `socio_reintegro_id` int(11) DEFAULT '0',
  `alicuota_comision_cobranza` decimal(10,3) DEFAULT '0.000',
  `comision_cobranza` decimal(10,2) DEFAULT '0.00',
  PRIMARY KEY (`id`),
  KEY `FK_liquidacion_cuotas_liquidacion` (`liquidacion_id`),
  KEY `FK_liquidacion_cuotas_socios` (`socio_id`),
  KEY `FK_liquidacion_cuotas_beneficio` (`persona_beneficio_id`),
  KEY `FK_liquidacion_cuotas_cuotas` (`orden_descuento_cuota_id`),
  KEY `FK_liquidacion_cuotas_proveedor` (`proveedor_id`),
  KEY `IDX_resumen_socio` (`liquidacion_id`,`codigo_organismo`,`socio_id`,`tipo_cuota`),
  KEY `idx_liquidacion_intercambio_id` (`liquidacion_intercambio_id`),
  KEY `idx_intercambio` (`socio_id`,`liquidacion_intercambio_id`),
  KEY `idx_imputacion_pagos` (`liquidacion_id`,`importe_debitado`,`liquidacion_intercambio_id`),
  KEY `idx_liquidacion_socio_registro` (`liquidacion_id`,`socio_id`,`registro`),
  KEY `idx_imputada` (`liquidacion_id`,`imputada`,`proveedor_id`),
  KEY `IDX_adicional_imputado` (`liquidacion_id`,`mutual_adicional_pendiente_id`,`orden_descuento_id`,`importe_debitado`,`imputada`),
  KEY `idx_listado_proveedor` (`liquidacion_id`,`proveedor_id`,`tipo_producto`,`tipo_cuota`),
  KEY `liquidacion_id` (`liquidacion_id`,`socio_id`,`para_imputar`,`imputada`),
  KEY `idx_liquidacion_cuotas_cobro_id` (`orden_descuento_cobro_id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

/*
alter table liquidacion_cuota_historicos disable keys;
insert into liquidacion_socio_historicos
select * from liquidacion_socios where liquidacion_id < 524;
alter table liquidacion_cuota_historicos enable keys;
*/


CREATE TABLE `liquidacion_socio_historicos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `liquidacion_id` int(11) DEFAULT '0',
  `registro` int(11) DEFAULT '1',
  `criterio_deuda` int(11) DEFAULT '0',
  `socio_id` int(11) DEFAULT '0',
  `persona_beneficio_id` int(11) DEFAULT '0',
  `codigo_organismo` varchar(12) DEFAULT NULL,
  `nro_ley` varchar(2) DEFAULT NULL,
  `tipo` varchar(1) DEFAULT NULL,
  `nro_beneficio` varchar(20) DEFAULT NULL,
  `sub_beneficio` varchar(2) DEFAULT NULL,
  `codigo_dto` varchar(10) DEFAULT '0',
  `sub_codigo` varchar(1) DEFAULT '0',
  `porcentaje` decimal(10,2) DEFAULT '100.00',
  `banco_id` varchar(5) DEFAULT NULL,
  `sucursal` varchar(5) DEFAULT NULL,
  `tipo_cta_bco` varchar(4) DEFAULT NULL,
  `nro_cta_bco` varchar(50) DEFAULT NULL,
  `cbu` varchar(23) DEFAULT NULL,
  `error_cbu` tinyint(1) DEFAULT '0',
  `tipo_documento` varchar(12) DEFAULT NULL,
  `documento` varchar(11) DEFAULT NULL,
  `apenom` varchar(100) DEFAULT NULL,
  `persona_id` int(11) DEFAULT '0',
  `cuit_cuil` varchar(11) DEFAULT NULL,
  `codigo_empresa` varchar(12) DEFAULT NULL,
  `codigo_reparticion` varchar(11) DEFAULT NULL,
  `turno_pago` varchar(12) DEFAULT NULL,
  `alta` tinyint(1) DEFAULT '0',
  `banco_intercambio` varchar(5) DEFAULT NULL,
  `periodo` tinyint(1) DEFAULT '0',
  `ultima_calificacion` varchar(12) DEFAULT NULL,
  `importe_dto` decimal(10,2) DEFAULT '0.00',
  `importe_adebitar` decimal(10,2) DEFAULT '0.00',
  `importe_debitado` decimal(10,2) DEFAULT '0.00',
  `importe_imputado` decimal(10,2) DEFAULT '0.00',
  `importe_reintegro` decimal(10,2) DEFAULT '0.00',
  `status` varchar(10) DEFAULT NULL,
  `indica_pago` tinyint(1) DEFAULT '0',
  `fecha_pago` date DEFAULT NULL,
  `liquidacion_intercambio_id` int(11) DEFAULT '0',
  `imputada` tinyint(1) DEFAULT '0',
  `orden_descuento_cobro_id` int(11) DEFAULT '0',
  `socio_calificacion_id` int(11) DEFAULT '0',
  `socio_reintegro_id` int(11) DEFAULT '0',
  `intercambio` text,
  `fecha_debito` date DEFAULT NULL,
  `diskette` tinyint(1) DEFAULT '1',
  `formula_criterio_deuda` text,
  `detalla` tinyint(1) DEFAULT '0',
  `fecha_otorgamiento` date DEFAULT NULL,
  `importe_total` decimal(10,2) DEFAULT '0.00',
  `cuotas` int(11) DEFAULT '0',
  `importe_cuota` decimal(10,2) DEFAULT '0.00',
  `importe_deuda` decimal(10,2) DEFAULT '0.00',
  `importe_deuda_vencida` decimal(10,2) DEFAULT '0.00',
  `importe_deuda_no_vencida` decimal(10,2) DEFAULT '0.00',
  `orden_descuento_id` int(11) DEFAULT '0',
  `error_intercambio` text,
  PRIMARY KEY (`id`),
  KEY `FK_liquidacion_socios_liquidacion` (`liquidacion_id`),
  KEY `FK_liquidacion_socios_socios` (`socio_id`),
  KEY `FK_liquidacion_socios_beneficio` (`persona_beneficio_id`),
  KEY `idx_documento` (`documento`),
  KEY `idx_apenom` (`apenom`),
  KEY `idx_producto_beneficio_socio` (`liquidacion_id`,`socio_id`,`persona_beneficio_id`),
  KEY `idx_debito` (`socio_id`,`codigo_organismo`,`nro_ley`,`tipo`,`nro_beneficio`,`sub_beneficio`,`codigo_dto`,`sub_codigo`,`banco_id`,`cbu`,`tipo_documento`,`documento`,`status`),
  KEY `idx_liquidacion_intercambio` (`liquidacion_intercambio_id`),
  KEY `idx_intercambio` (`socio_id`,`liquidacion_intercambio_id`),
  KEY `idx_liquidacion_id_status` (`liquidacion_id`,`status`,`liquidacion_intercambio_id`),
  KEY `idx_orden_cobro` (`liquidacion_id`,`orden_descuento_cobro_id`) USING BTREE,
  KEY `idx_pagos_no_imputados` (`liquidacion_id`,`socio_id`,`importe_debitado`,`liquidacion_intercambio_id`,`imputada`) USING BTREE,
  KEY `idx_reintegro` (`liquidacion_id`,`importe_reintegro`,`liquidacion_intercambio_id`),
  KEY `idx_liquidacion_socio_alta` (`liquidacion_id`,`socio_id`,`alta`),
  KEY `idx_liquidacion_alta` (`liquidacion_id`,`alta`,`indica_pago`),
  KEY `idx_orden_descuento_id` (`orden_descuento_id`),
  KEY `idx_empresa` (`codigo_empresa`,`codigo_reparticion`,`turno_pago`),
  KEY `idx_liquidacion_beneficio_turno` (`liquidacion_id`,`persona_beneficio_id`,`turno_pago`),
  KEY `idx_liquidacion_diskette` (`liquidacion_id`,`diskette`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


CREATE TABLE `liquidacion_socio_rendicion_historicos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `periodo` varchar(6) DEFAULT NULL,
  `liquidacion_id` int(11) DEFAULT '0',
  `liquidacion_intercambio_id` int(11) DEFAULT '0',
  `socio_id` int(11) DEFAULT '0',
  `codigo_organismo` varchar(12) DEFAULT NULL,
  `nro_ley` varchar(2) DEFAULT NULL,
  `tipo` varchar(1) DEFAULT NULL,
  `nro_beneficio` varchar(20) DEFAULT NULL,
  `sub_beneficio` varchar(2) DEFAULT NULL,
  `codigo_dto` varchar(10) DEFAULT '0',
  `sub_codigo` varchar(1) DEFAULT '0',
  `porcentaje` decimal(10,2) DEFAULT '100.00',
  `banco_id` varchar(5) DEFAULT NULL,
  `sucursal` varchar(5) DEFAULT NULL,
  `tipo_cta_bco` varchar(4) DEFAULT NULL,
  `nro_cta_bco` varchar(50) DEFAULT NULL,
  `cbu` varchar(23) DEFAULT NULL,
  `documento` varchar(11) DEFAULT NULL,
  `banco_intercambio` varchar(5) DEFAULT NULL,
  `importe_debitado` decimal(10,2) DEFAULT '0.00',
  `status` varchar(10) DEFAULT NULL,
  `indica_pago` tinyint(1) DEFAULT '0',
  `fecha_debito` date DEFAULT NULL,
  `registro` varchar(200) DEFAULT NULL,
  `orden_descuento_cobro_id` int(11) DEFAULT '0',
  `orden_descuento_id` int(11) DEFAULT '0',
  `nro_cuota` int(11) DEFAULT '0',
  `proveedor_id` int(11) DEFAULT '0',
  `saldo_operacion_informado` decimal(10,2) DEFAULT '0.00',
  PRIMARY KEY (`id`),
  KEY `IDX_1` (`liquidacion_id`,`documento`),
  KEY `idx_4` (`liquidacion_id`),
  KEY `idx_5` (`liquidacion_id`,`socio_id`,`banco_id`,`documento`,`status`),
  KEY `idx_2` (`liquidacion_id`,`socio_id`,`indica_pago`),
  KEY `idx_3` (`socio_id`,`periodo`,`indica_pago`),
  KEY `idx_6` (`banco_intercambio`,`status`),
  KEY `idx_7` (`socio_id`),
  KEY `idx_8` (`liquidacion_intercambio_id`),
  KEY `idx_orden_descuento_id` (`orden_descuento_id`),
  KEY `idx_9` (`cbu`,`banco_intercambio`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;



CREATE TABLE `liquidacion_intercambio_historicos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `liquidacion_id` int(11) DEFAULT '0',
  `codigo_organismo` varchar(12) DEFAULT NULL,
  `periodo` varchar(8) DEFAULT NULL,
  `banco_id` varchar(5) DEFAULT NULL,
  `archivo_nombre` varchar(100) DEFAULT NULL,
  `archivo_file` varchar(100) DEFAULT NULL,
  `target_path` varchar(200) DEFAULT NULL,
  `observaciones` text,
  `fragmentado` tinyint(1) DEFAULT '0',
  `procesado` tinyint(1) DEFAULT '0',
  `total_registros` int(10) DEFAULT '0',
  `registros_cobrados` int(10) DEFAULT '0',
  `importe_cobrado` decimal(15,2) DEFAULT '0.00',
  `recibo_id` int(11) DEFAULT '0',
  `proveedor_id` int(11) DEFAULT '0',
  `lote` longtext,
  `user_created` varchar(50) DEFAULT NULL,
  `user_modified` varchar(50) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `liquidacion_socio_envio_registro_historicos` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `liquidacion_socio_envio_id` int(11) DEFAULT '0',
  `liquidacion_socio_id` int(11) DEFAULT '0',
  `socio_id` int(11) DEFAULT NULL,
  `identificador_debito` char(22) DEFAULT NULL,
  `importe_adebitar` decimal(10,2) DEFAULT '0.00',
  `registro` text,
  `excluido` tinyint(1) DEFAULT '0',
  `motivo` text,
  `user_created` varchar(50) DEFAULT NULL,
  `user_modified` varchar(50) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `codigo_rendicion` varchar(3) DEFAULT NULL,
  `descripcion_codigo` varchar(200) DEFAULT NULL,
  `procesado` tinyint(1) DEFAULT '0',
  `fecha_proceso` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_liquidacion_socios` (`liquidacion_socio_id`),
  KEY `fk_liquidacion_socio_envio_id` (`liquidacion_socio_envio_id`),
  KEY `idx_identificador_debito` (`identificador_debito`),
  KEY `idx_excluido` (`excluido`),
  KEY `FK_LIQUIDACION_SOCIO_SOCIO_ID` (`socio_id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `liquidacion_socio_envio_historicos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `asincrono_id` int(11) DEFAULT '0',
  `bloqueado` tinyint(1) DEFAULT '0',
  `liquidacion_id` int(11) DEFAULT NULL,
  `banco_id` varchar(5) DEFAULT NULL,
  `banco_nombre` varchar(100) DEFAULT NULL,
  `fecha_debito` date DEFAULT NULL,
  `cantidad_registros` int(11) DEFAULT '0',
  `status` varchar(5) DEFAULT NULL,
  `importe_debito` decimal(10,2) DEFAULT '0.00',
  `observaciones` text,
  `longitud_registro` int(11) DEFAULT '0',
  `uuid` varchar(20) DEFAULT NULL,
  `lote` longtext,
  `archivo` varchar(100) DEFAULT NULL,
  `user_created` varchar(50) DEFAULT NULL,
  `user_modified` varchar(50) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_uuid` (`uuid`),
  KEY `fk_liquidacion_id` (`liquidacion_id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


CREATE TABLE `liquidacion_socio_score_historicos` (
  `liquidacion_id` int(11) NOT NULL,
  `socio_id` int(11) NOT NULL,
  `13` decimal(10,2) NOT NULL DEFAULT '0.00',
  `12` decimal(10,2) NOT NULL DEFAULT '0.00',
  `09` decimal(10,2) NOT NULL DEFAULT '0.00',
  `06` decimal(10,2) NOT NULL DEFAULT '0.00',
  `03` decimal(10,2) NOT NULL DEFAULT '0.00',
  `00` decimal(10,2) NOT NULL DEFAULT '0.00',
  `cargos_adicionales` decimal(10,2) NOT NULL DEFAULT '0.00',
  `saldo_actual` decimal(10,2) DEFAULT NULL,
  `riesgo` int(11) NOT NULL DEFAULT '0',
  `score` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`liquidacion_id`,`socio_id`),
  KEY `fk_liquidacion_socio_scores_2_idx` (`socio_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
