CREATE DEFINER=`root`@`localhost` FUNCTION `F_PAGO_CUOTA`(
	vSOLICITADO DECIMAL(10,2),
    vCUOTAS INT(11),
    vTASA DECIMAL(10,4),
    vPORCENTAJE_ADICIONAL DECIMAL(10,3),
    vIVA DECIMAL(10,2),
    vTIPO CHAR(3)
	) RETURNS decimal(10,2)
    DETERMINISTIC
BEGIN
	-- select F_PAGO_CUOTA(1000,3,11.55,18,21);
	SET @VALOR_CUOTA = 0;
	
    SET vPORCENTAJE_ADICIONAL = vPORCENTAJE_ADICIONAL / 100;
	SET vIVA = vIVA / 100;
    SET vTASA = vTASA / 100;
    
	SET @CAPITAL = vSOLICITADO * (1 + vPORCENTAJE_ADICIONAL);
	SET @CALCULO = ROUND((@CAPITAL * vTASA) / (1 - (POW(1 + vTASA, vCUOTAS * -1))),2);
    SET @INTERES = ROUND(@CALCULO * vTASA,2);
    SET @IVA = ROUND(@INTERES * vIVA,2);
    SET @INTERES = ROUND(@INTERES - @IVA,2);
    SET @ADICIONALES = ROUND(@CALCULO * vPORCENTAJE_ADICIONAL,2);
    SET @CAPITAL_CUOTA = @CALCULO - (@INTERES + @IVA + @ADICIONALES);
    SET @VALOR_CUOTA = @INTERES + @IVA + @ADICIONALES + @CAPITAL_CUOTA;

	SET vSOLICITADO = ROUND(vSOLICITADO,2);
    SET @CAPITAL = ROUND(@CAPITAL,2);
    SET @VALOR_CUOTA = ROUND(@VALOR_CUOTA,2);
    SET @CAPITAL_CUOTA = ROUND(@CAPITAL_CUOTA,2);
    SET @INTERES = ROUND(@INTERES,2);
    SET @ADICIONALES = ROUND(@ADICIONALES,2);
    SET @IVA = ROUND(@IVA,2);
	
    IF vTIPO = 'CAP' THEN
		RETURN IFNULL(@CAPITAL_CUOTA,0);
	END IF;
    IF vTIPO = 'INT' THEN
		RETURN IFNULL(@INTERES,0);
	END IF;    
    IF vTIPO = 'IVA' THEN
		RETURN IFNULL(@IVA,0);
	END IF;  
    IF vTIPO = 'ADI' THEN
		RETURN IFNULL(@ADICIONALES,0);
	END IF;     
    IF vTIPO = 'CUO' THEN
		RETURN IFNULL(@VALOR_CUOTA,0);
	END IF;    
    
    END